# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
options:
    size:
        description: |
            Size of memcache pool in MiB (memcached option -m)
            Values smaller than 64 are not valid
        type: int
        default: 768
    connection-limit:
        description: |
            maximum simultaneous connections (memcached option -c)
            0 or negative values are not valid.
        type: int
        default: 1024
    request-limit:
        description: |
            limit of requests a single client can make at one time (memcached option -R)
            0 or negative values are not valid.
        type: int
        default: 20
    tcp-port:
        description: |
            TCP port to listen on (memcached option -p)
        type: int
        default: 11211
    udp-port:
        description: |
            UDP port to listen on (memcached option -U)
            0 or invalid port disable udp listener
        type: int
        default: 0
    threads:
        description: |
            number of threads to use. (memcached option -t)
            0 or negative values are not valid.
        type: int
        default: 4
    ssl-cert:
        type: string
        default:
        description: |
            Base64 encoded SSL certificate to use with memcached. Setting this
            value and ssl_key will TLS connection to memcached.
            NOTE: TLS is not currently supported by the memcache interface.
    ssl-key:
        type: string
        default:
        description: |
            Base64 encoded SSL key to use with certificate specified as ssl-cert.
            This is oonly required if the key is not part oof the ssl-cert
    ssl-ca:
        type: string
        default:
        description: |
            SSL CA to use with the certificate and key provided - this is only
            required if you are providing a privately signed ssl-cert and ssl-key.
