# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
options:
    size:
        description: |
            Size of memcache pool in MiB (memcached option -m)
            Values smaller than 64, default to 64 (memcached minimum requirement)
        type: int
        default: 768
    connection-limit:
        description: |
            maximum simultaneous connections (memcached option -c)
            0 or negative values take to the memcached default (1024)
        type: int
        default: 1024
    request-limit:
        description: |
            limit of requests a single client can make at one time (memcached option -R)
            0 or negative values take to the memcached default (20)
        type: int
        default: 20
    tcp-port:
        description: |
            TCP port to listen on (memcached option -p)
            Invalid tcp ports take to the memcached default (11211)
        type: int
        default: 11211
    udp-port:
        description: |
            UDP port to listen on (memcached option -U)
            0 or invalid port disable udp listener
        type: int
        default: 0
    threads:
        description: |
            number of threads to use. (memcached option -t)
            0 or negative values take to the memcached default (4)
        type: int
        default: 4

